### ISSUE TITLE
【BUG】运行报错: "{"message":"Internal Error"}"

### ISSUE THREAD

**Issue by zwluoqi** [Soulter/hugging-chat-api#1]
运行测试代码，有以下错误：
```
{"conversationId":"644db6a65666977e279f5904"}
{"message":"Internal Error"}
None
[]
```
是不是要配置？

**Comment by Soulter** [comment]
已找到问题，huggingchat最近修改了他们的请求字段，我马上修复

**Comment by Soulter** [comment]
已解决，请使用
```
pip install hugchat --upgrade -i https://pypi.org/simple
```
更新

**Comment by zwluoqi** [comment]
好的 ，幸苦了，api网址能分享下吗，我想改成C#用用。
> 已找到问题，huggingchat最近修改了他们的请求字段，我马上修复

**Comment by Soulter** [comment]
没有提供公开的api，我是通过抓包拿到的，网址是这个: https://huggingface.co/chat

**Comment by zwluoqi** [comment]
```
        req_json = {
            "inputs": text,
            "parameters": {
                "temperature": temperature,
                "top_p": top_p,
                "repetition_penalty": repetition_penalty,
                "top_k": top_k,
                "truncate": truncate,
                "watermark": False,
                "max_new_tokens": 1024,
                "stop": ["</s>"],
                "return_full_text": False,
                "stream": True,
            },
            "options": {
                    "use_cache": False,
                    "is_retry": False,
                    "id": str(uuid.uuid4()),
            },
        }
```
这个input只是需要当前的发送信息就可以了，上下文在hugging那边记录。就是不能向chatgpt那样，自己构建上下文是把？

**Comment by Soulter** [comment]
> ```
>         req_json = {
>             "inputs": text,
>             "parameters": {
>                 "temperature": temperature,
>                 "top_p": top_p,
>                 "repetition_penalty": repetition_penalty,
>                 "top_k": top_k,
>                 "truncate": truncate,
>                 "watermark": False,
>                 "max_new_tokens": 1024,
>                 "stop": ["</s>"],
>                 "return_full_text": False,
>                 "stream": True,
>             },
>             "options": {
>                     "use_cache": False,
>                     "is_retry": False,
>                     "id": str(uuid.uuid4()),
>             },
>         }
> ```
> 
> 这个input只是需要当前的发送信息就可以了，上下文在hugging那边记录。就是不能向chatgpt那样，自己构建上下文是把？

对，应该是这样的
