### ISSUE TITLE
Support for Mistral 7B?

### ISSUE THREAD

**Issue by babycommando** [Soulter/hugging-chat-api#106]
![image](https://github.com/Soulter/hugging-chat-api/assets/71618056/b3420c25-fce0-4568-8840-7848af5a9a0b)

Does it already support it?

**Comment by ogios** [comment]
#105

**Comment by hansfzlorenzana** [comment]
I think #105 is not yet merged, thus the new model is not yet added to the current version of this api.

**Comment by Soulter** [comment]
#105 has been merged, please update to the latest version v0.3.2.

**Comment by Whitelisted1** [comment]
Can we close this issue? It seems like it has been resolved
