### ISSUE TITLE
Support for Zephyr - fine tune of Mistral (replaced Mistral)

### ISSUE THREAD

**Issue by hansfzlorenzana** [Soulter/hugging-chat-api#111]
<img width="499" alt="image" src="https://github.com/Soulter/hugging-chat-api/assets/47592497/16915fd6-34b9-4202-a73d-dca48f5836a7">

Please add support to this. HugChat updated the list of usable models.

**Comment by Whitelisted1** [comment]
With a recent release, [v0.3.2](https://github.com/Soulter/hugging-chat-api/releases/tag/v0.3.2), the hugchat module now automatically fetches the available LLMs from the HuggingChat servers. You can see this with the following line of code:
```python
print(chatbot.get_available_llm_models())
```
