### ISSUE TITLE
from hugchat import hugchat 'type' object is not subscriptable

### ISSUE THREAD

**Issue by KristiKovacs** [Soulter/hugging-chat-api#116]
Running locally using Anaconda Pycharm.

The following packages in my requirements.txt:
```
streamlit>=1.26.0
hugchat
streamlit-chat
streamlit-extras
```

Error happening at:

```from hugchat import hugchat```

Error message:

> TypeError: 'type' object is not subscriptable
> Traceback:
> File "/Users/me/Desktop/SnowChatbox/venv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
>     exec(code, module.__dict__)
> File "/Users/me/Desktop/SnowChatbox/LLM_Chatbox/streamlit_app.py", line 2, in <module>
>     from hugchat import hugchat
> File "/Users/me/Desktop/SnowChatbox/venv/lib/python3.8/site-packages/hugchat/hugchat.py", line 18, in <module>
>     class QueryResult:
> File "/Users/me/Desktop/SnowChatbox/venv/lib/python3.8/site-packages/hugchat/hugchat.py", line 24, in QueryResult
>     web_search_sources: list[WebSearchSource]
>

**Comment by KristiKovacs** [comment]
It turns out it was my Python version, I had 3.8 and I don't see this error with 3.9

**Comment by Soulter** [comment]
That's a bug, some new features in recent versions use new syntaxes that 3.6, 3.7 and 3.8 haven't. We will fix the problem.

https://github.com/Soulter/hugging-chat-api/actions/runs/6557522438/job/17809291093

**Comment by Soulter** [comment]
Solved
