### ISSUE TITLE
CLI is broken

### ISSUE THREAD

**Issue by Whitelisted1** [Soulter/hugging-chat-api#126]
It does not take long to notice that the CLI is broken and pretty much unusable, just try most of the commands available through the `/help` menu in the CLI.
Personally, I think that the CLI is not entirely needed as the user can just go to the [HuggingChat UI](https://huggingface.co/chat) and talk with the models there. Because of this, I suggest that we remove the CLI, although I can understand if that is unwanted.

**Comment by ogios** [comment]
most of the time i use cli to do some tests, but that's before unit tests

**Comment by Whitelisted1** [comment]
Yes, but how practical is the CLI for general use? Most of the CLI is already broken.

**Comment by Whitelisted1** [comment]
I'm working on this, I'll open a PR once it's done
