### ISSUE TITLE
Sending too many messages error

### ISSUE THREAD

**Issue by Vicccai** [Soulter/hugging-chat-api#130]
Hi. I am running a basic example (with my email and passwd inputted appropriately):

```
from hugchat import hugchat
from hugchat.login import Login

sign = Login(user, pass)
cookies = sign.login()

chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

query_result = chatbot.chat("Hi!")
print(query_result) # or query_result.text or query_result["text"]
```

I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 414, in _stream_query
    _type = obj['type']
            ~~~^^^^^^^^
KeyError: 'type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 414, in _stream_query
    _type = obj['type']
            ~~~^^^^^^^^
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Desktop/ChatBot.py", line 11, in <module>
    query_result = chatbot.chat("Hi!")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 637, in chat
    return self.query(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 582, in query
    return self._non_stream_query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 490, in _non_stream_query
    for resp in self._stream_query(
  File "/usr/local/lib/python3.11/site-packages/hugchat/hugchat.py", line 443, in _stream_query
    raise ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"message":"You are sending too many messages. Try again later."}


When I go to HuggingChat online, I see just a series of 15 of the same message (Hi!) in the most recent conversation. How can I fix this?

**Comment by ogios** [comment]
it has request rate limit which means you can only send certain amount of request in a certain amount of time.
but i dont really know what strategy it sets, whether it's related to your ip address or just your account.

for now, just reduce your usage of huggingchat (in this account).

**Comment by Vicccai** [comment]
Hi, thanks for the reply. The issue is that each time I call chatbot.chat('Hi!'), it sends the Hi message 15+ times, which leads to the error. I never get a response back.

**Comment by kwon514** [comment]
I get this same issue - with the message being sent many times when I look on the HuggingFace website. This seems to be an issue that has popped up recently - this did not happen previously.

**Comment by p2d0** [comment]
> Hi, thanks for the reply. The issue is that each time I call chatbot.chat('Hi!'), it sends the Hi message 15+ times, which leads to the error. I never get a response back, even if it's the first time I call chat().

Same

**Comment by Whitelisted1** [comment]
This seems similar to [this](https://github.com/Soulter/hugging-chat-api/issues/122#issuecomment-1769475704) comment I left on another issue. I did some testing, though, and was unable to reproduce it now.
How often are these messages happening?

**Comment by kwon514** [comment]
Oddly enough, I'm also unable to reproduce it now within the past 2ish hours, despite still having issues until then.

**Comment by Vicccai** [comment]
I think what happened is Hugging Chat sometimes is down/slow. Last night I was receiving network error on Hugging Chat and wouldn't get any responses. I think the way the API works is it resends the request if it doesn't receive a response, hence the sending too many messages. It's working fine now, with no network error on Hugging Chat.

**Comment by MUZAMMILPERVAIZ** [comment]
I am also receiving this error on first query

**Comment by Whitelisted1** [comment]
Perhaps this error is due to issues with the HuggingChat servers. If you see the attached video, you will see that I am having a similar error with both the [HuggingChat UI](https://huggingface.co/chat) and with the `hugchat` library

https://github.com/Soulter/hugging-chat-api/assets/77711834/c8d4d74a-4987-42ea-8a48-5393018af134
