### ISSUE TITLE
Support for Mixtral 8x7B

### ISSUE THREAD

**Issue by tomjuggler** [Soulter/hugging-chat-api#146]
Not sure how easy it is to add models, but this one is proving the best so far, and is available on Hugging Chat. 

Model: [mistralai/Mixtral-8x7B-Instruct-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1)

**Comment by Soulter** [comment]
Hi, this function may meet your demand.
```py
# Get the available models (not hardcore)
models: list = chatbot.get_available_llm_models()

# Switch model to the given index
chatbot.switch_llm(0) # Switch to the first model
chatbot.switch_llm(1) # Switch to the second model
```

**Comment by tomjuggler** [comment]
['meta-llama/Llama-2-70b-chat-hf', 'OpenAssistant/oasst-sft-6-llama-30b-xor', 'codellama/CodeLlama-34b-Instruct-hf', 'tiiuae/falcon-180B-chat']

Those are the only ones available from chatbot.get_available_llm_models(), is there a way to have Mixtral 8x7B show up here?

**Comment by Soulter** [comment]
What version of hugchat are you using?
```bash
pip3 show hugchat
```

**Comment by tomjuggler** [comment]
So sorry I just updated and it's option 5 on the list.
