### ISSUE TITLE
STUCK WITH THIS ERROR [Error] Failed to create new conversation. Retrying... (6)

### ISSUE THREAD

**Issue by AnaghaAMT** [Soulter/hugging-chat-api#151]
Please provide a solution to this issue.

**Comment by yanis112** [comment]
Can you provide more infos ? Your code for exemple ?

**Comment by yanis112** [comment]
If you cannot create a new conversation, try deleting all your past conversations because you probably reached the maximum amount (you can do it manually in the huggingchat web interface *sure method* or use the delete function in the api *not sure*)
