### ISSUE TITLE
how do i make it remember previous messages like chatgpt

### ISSUE THREAD

**Issue by YoussefBechara** [Soulter/hugging-chat-api#167]
helpppppppppp

**Comment by Whitelisted1** [comment]
I'm sorry, but you didn't provide any information about your issue, and seem to have selected an incorrect label. Can you please provide more information about the problems you are having?

**Comment by Soulter** [comment]
Hello, it defaults to remember your previous message. Are you encountered any problem?

**Comment by rezkanas** [comment]
@YoussefBechara where do you add that conv ID, and how do you get it in the first place? 

I have this function and when ever i call it, it starts a new conversation. I am trying now to control it with  chatbot.new_conversation(switch_to=True)...  any idea how to make it stick to one conversation thread?


```
from hugchat import hugchat
from hugchat.login import Login
import os
from dotenv import load_dotenv, find_dotenv

# read local .env file
_ = load_dotenv(find_dotenv())

def query_LLM(prompt, new_conversation: bool = False):
    # Log in to huggingface and grant authorization to huggingchat
    huggingchat_user_email = os.environ['huggingchat_user_email']
    huggingchat_user_pwd = os.environ['huggingchat_user_pwd']

    sign = Login(email=huggingchat_user_email, passwd=huggingchat_user_pwd)
    cookies = sign.login()

    # Save cookies to the local directory
    cookie_path_dir = "./cookies_snapshot"
    sign.saveCookiesToDir(cookie_path_dir)

    # Create a ChatBot
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"
    if new_conversation:
        chatbot.new_conversation(switch_to=True)
    # non stream response
    return chatbot.chat(prompt)['text']

```

**Comment by YoussefBechara** [comment]
@rezkanas 
use these two lines: id = chatbot.new_conversation()
print(id)
chatbot.change_conversation(id)
 Here we are making the new conv with id printed then we copy it and change ttje conv to it and yea

**Comment by rezkanas** [comment]
Thank you @YoussefBechara. 
I update my code and continuing in the same conversation is working now. but a new requirements pops up now. I need to change system prompt for each round of conversation. I have a go at it but I see that it does not work when running the code. 


```
    @staticmethod
    def query_LLM(system_prompt: str, prompt: str, new_conversation: bool = False):
        # Log in to huggingface and grant authorization to huggingchat
        huggingchat_user_email = os.environ['huggingchat_user_email']
        huggingchat_user_pwd = os.environ['huggingchat_user_pwd']

        sign = Login(email=huggingchat_user_email, passwd=huggingchat_user_pwd)
        cookies = sign.login()

        # Save cookies to the local directory
        cookie_path_dir = "./cookies_snapshot"
        sign.saveCookiesToDir(cookie_path_dir)

        # Create a ChatBot
        if new_conversation:
            global conversation_id, chatbot
            chatbot = hugchat.ChatBot(system_prompt=system_prompt,
                                      cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"

            chatbot.new_conversation(switch_to=True)
            conversation_id = chatbot.new_conversation()
        else:
            #for continuing conversation, change system prompt
            chatbot.system_prompt=system_prompt

        chatbot.change_conversation(conversation_id)

        return chatbot.chat(prompt)['text']
```

**Comment by rezkanas** [comment]
@Soulter, any update about this?

**Comment by YoussefBechara** [comment]
@rezkanas what are system prompts? because it doesnt ask me anything i just send normal promptsto the same conversation again and again

**Comment by rezkanas** [comment]
I would like to pass different system prompts at each turn of the conversation along with passing user prompts.  

However, I've noticed that when I attempt to change the `chatbot.system_prompt`, the language model (LLM) doesn't seem to adjust its responses accordingly. Could it be that the system prompt can't be changed mid-conversation? I need confirmation or clarification on this matter. I think changing the system prompt mid-conversation isn't directly supported.

**Comment by Whitelisted1** [comment]
> I would like to pass different system prompts at each turn of the conversation along with passing user prompts.  
> 
> 
> 
> However, I've noticed that when I attempt to change the `chatbot.system_prompt`, the language model (LLM) doesn't seem to adjust its responses accordingly. Could it be that the system prompt can't be changed mid-conversation? I need confirmation or clarification on this matter. I think changing the system prompt mid-conversation isn't directly supported.
> 
> 

No, with the current way that HuggingFace manages system prompts you can only use one system prompt per conversation.

**Comment by rezkanas** [comment]
thank you @Whitelisted1.
