### ISSUE TITLE
Reuse existing login token during hot reload

### ISSUE THREAD

**Issue by CorporateDrone** [Soulter/hugging-chat-api#168]
**Is your feature request related to a problem? Please describe.**
While I'm working on my app, I'm using hot reload. This causes hugging-chat-ui to log in every time I save my app. I get an email from hugging face every stating that I've logged into a new device every time.

**Describe the solution you'd like**
Can Login try to use the previous token stored in <userid>.json when the app first starts. If it's not valid, login for a new token

**Describe alternatives you've considered**
**I've use this for signing in**
`sign = Login(email, passwd)
cookies = sign.login()

**Save cookies to the local directory**
cookie_path_dir = "./cookies_snapshot"
sign.saveCookiesToDir(cookie_path_dir)`

**and tried pointing to the cookies json file, but it still logs in again after each reload.**
`chatbot = hugchat.ChatBot(cookie_path=f"/cookies_snapshot/{email}.json" )` 

I also tried
`chatbot = hugchat.ChatBot(cookies=cookies.get_dict())`

**Additional context**
I save throughout my work session, which spams my inbox.

**Comment by Soulter** [comment]
hello, in current version there have some ways to reach this effect:
```py
from hugchat import hugchat
from hugchat.login import Login

cookies_dir = "./cookies"
sign = Login("test@example.com", "pwd")
cookies = None
try:
    cookies = sign.loadCookiesFromDir(cookies_dir) # load cookies from <email>.json
except BaseException:
    cookies = sign.login()
    sign.saveCookiesToDir(cookies_dir) # named as: <email>.json

chatbot = hugchat.ChatBot(cookies=cookies)  # or cookie_path="usercookies/<email>.json"

```

(but it doesn't seem concise, I'll improve it)
