### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Soulter** [Soulter/hugging-chat-api#169]
**Describe the bug**
Something went wrong while executing login().

```bash
Traceback (most recent call last):
  File "/Users/soulter/Documents/testhugchat.py", line 8, in <module>
    cookies = sign.login()
  File "/Users/soulter/Library/Python/3.9/lib/python/site-packages/hugchat/login.py", line 126, in login
    location = self.getAuthURL()
  File "/Users/soulter/Library/Python/3.9/lib/python/site-packages/hugchat/login.py", line 94, in getAuthURL
    raise Exception("Something went wrong!")
Exception: Something went wrong!
```

**To Reproduce**

```py
from hugchat import hugchat
from hugchat.login import Login

sign = Login("***", "***")
cookies = sign.login()
```

**Expected behavior**
Login successfully

**Comment by mahi141414** [comment]
![image](https://github.com/Soulter/hugging-chat-api/assets/134068589/078b113b-96f0-491f-885e-6d1af8e04740)

it's a bug in hugging face maybe :)

**Comment by Soulter** [comment]
> ![image](https://private-user-images.githubusercontent.com/134068589/304307646-078b113b-96f0-491f-885e-6d1af8e04740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDczMzEsIm5iZiI6MTcwNzgwNzAzMSwicGF0aCI6Ii8xMzQwNjg1ODkvMzA0MzA3NjQ2LTA3OGIxMTNiLTk2ZjAtNDkxZi04ODVlLTZkMWFmOGUwNDc0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwNjUwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODU2ZDRmOGJiOTQxZTI4NTNiZTExODk0OTVjNDE4YjFhMDI1ZmMyZTNmNjYyNjdjMDg5YmIwYzY4ODVlMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eLLW4jLGgYAAG2_o8ami2VXxKOLGNOtDgMDM_5jVW1Q)
> 
> it's a bug in hugging face maybe :)

Maybe. And I can't open the huggingchat website https://huggingface.co/chat/, it keeps getting stuck on preparing space. :/

**Comment by AravindRohit** [comment]
Yeah for me also

**Comment by Soulter** [comment]
The problem has been solved.

**Comment by Sriharan-S** [comment]
> The problem has been solved.

can you tell me how bro? im also facing this issue :(
