### ISSUE TITLE
Internal error 

### ISSUE THREAD

**Issue by FERRAMOS888** [Soulter/hugging-chat-api#173]
The chatbot return internal server error 

xception ignorada en: <objeto generador ChatBot._stream_query en 0x000001E1BAB3B6A0>
Rastreo (última llamada más reciente):
Archivo "C:\Users\Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat. py", línea 730, en _stream_query
hugchat.exceptions.ChatError: No se pudo analizar la respuesta: {"message":"Error interno"}

C:\Users\Migue\Desktop\EduBot>py ia.py
Usted: e
ERROR:root:No typeencontrado en respuesta: {'message': 'Error interno'}
Bot: Rastreo (última llamada más reciente):
Archivo "C :\Users\Migue\Desktop\EduBot\ia.py", línea 28, en
print("Bot:", query_result)
Archivo "C:\Users\Migue\AppData\Local\Programs\Python\Python311\Lib\site -packages\hugchat\message.py", línea 228, en str
devuelve self.wait_until_done()
^^^^^^^^^^^^^^^^^^^^^^
Archivo "C:\Users\ Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", línea 194, en wait_until_done
self. next ()
Archivo "C:\Users\Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", línea 149, en el siguiente
aumento self.error
Archivo "C:\Users \Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", línea 100, en el siguiente
self._filterResponse(a)
Archivo "C:\Users\Migue\AppData\Local\ Programs\Python\Python311\Lib\site-packages\hugchat\message.py", línea 85, en _filterResponse
levanta ChatError(f"El servidor devuelve un error: {obj['message']}")
hugchat.exceptions.ChatError: El servidor devuelve un error: Seguimiento de error interno
(última llamada más reciente):

**Comment by Soulter** [comment]
duplicate of #171
