### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by hansen-innovation** [Soulter/hugging-chat-api#18]
Hi! Thanks for sharing this project! 

What is the model that is behind this hugging chat API? The same as the hugging-chat website: OpenAssistant/oasst-sft-6-llama-30b? Thank you!

**Comment by Soulter** [comment]
The default model used by this API is `OpenAssistant/oasis sft-6-llama-30b-xor` from Hugging Face
I will make it support custom models in the future.
