### ISSUE TITLE
Web search not working.

### ISSUE THREAD

**Issue by FBRDCYB3R** [Soulter/hugging-chat-api#187]
I am using the outline provided in the readme, and I am able to access the site but its not able to search the web. When I ask it "todays news" it defaults to the date of August 13, 2023 and nor am I able to switch llm, it keeps defaulting to Mistral Ai, even when I specify
`chatbot.switch_llm(1) # Switch to the second model

# Get information about the current conversation
#info = chatbot.get_conversation_info()
#print(info.id, info.title, info.model, info.system_prompt, info.history)

# Assistant
    assistant = chatbot.search_assistant(assistant_name="ChatGpt") # assistant name list in https://huggingface.co/chat/assistants
    assistant_list = chatbot.get_assistant_list_by_page(page=0)
    chatbot.new_conversation(assistant=assistant, switch_to=True) # create a new conversation with assistant
` 
and here is my version of the code I changed up a bit:

`from hugchat import hugchat
from hugchat.login import Login

# Log in to huggingface and grant authorization to huggingchat
EMAIL = "Kuzeshell69@gmail.com"
PASSWD = "Wordpass197900"
cookie_path_dir = "./cookies"
sign = Login(EMAIL, PASSWD)
cookies = sign.login(cookie_dir_path=cookie_path_dir, save_cookies=True)

# Create your ChatBot
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

# Function to get user input for query
def get_user_query():
    query = input("Enter your query: ")
    return query

# Main loop
while True:
    user_query = get_user_query()
    if user_query.lower() == "quit":
        break

    # Non-stream response
    query_result = chatbot.chat(user_query)
    print(query_result)

    # Stream response
    print("Streaming response:")
    response_text = ""
    for resp in chatbot.query(user_query, stream=True):
        if resp.get("type") == "stream" and resp.get("token"):
            response_text += resp["token"]
    print(response_text)
    chatbot.switch_llm(1) # Switch to the second model

# Get information about the current conversation
#info = chatbot.get_conversation_info()
#print(info.id, info.title, info.model, info.system_prompt, info.history)

# Assistant
    assistant = chatbot.search_assistant(assistant_name="ChatGpt") # assistant name list in https://huggingface.co/chat/assistants
    assistant_list = chatbot.get_assistant_list_by_page(page=0)
    chatbot.new_conversation(assistant=assistant, switch_to=True) # create a new conversation with assistant

    # Web search (new feature)
    query_result = chatbot.query(user_query, web_search=True)
    print("\nWeb search results:")
    for source in query_result.web_search_sources:
        print(f"Link: {source.link}")
        print(f"Title: {source.title}")
        print(f"Hostname: {source.hostname}")
        print()

`

**Comment by reflectored** [comment]
@Soulter if nobody works on this I can give it a try.

**Comment by cakemooner** [comment]
@reflectored Please look into. I have the same issue as you do.

**Comment by Soulter** [comment]
> @Soulter if nobody works on this I can give it a try.

hi, I've been a little bit busy recently so I didn't pay much attention to this issue timely, I'd appreciate it if you can work on this

**Comment by cakemooner** [comment]
When Web Search tries multiple sites and encounters one or more "Failed to parse webpage" errors, it should ignore the error and carry on to try next site. However currently the error is caught and raised. That's why it crashes out.

**Comment by Soulter** [comment]
I published a new version v0.4.2 that fixed the bug. Thanks @reflectored
