### ISSUE TITLE
switch_llm not working

### ISSUE THREAD

**Issue by shirindehghani** [Soulter/hugging-chat-api#190]
**Describe the bug**
Hello. I hope you are well and healthy.

It seems that the switch_llm function is not working properly and is unable to change the model.

**Comment by Whitelisted1** [comment]
After you use the `chatbot.switch_llm(index)` function you need to make sure you create a new conversation to actually use it. If you want a one-liner, you could use `chatbot.new_conversation(switch_to=True, modelIndex=index)`.
