### ISSUE TITLE
Can't Use My Own Assistant

### ISSUE THREAD

**Issue by Krovikan-Vamp** [Soulter/hugging-chat-api#192]
**Is your feature request related to a problem? Please describe.**

It seems there are some missing features related to using your own 'public' Assistants. I've created one that I can see on my account and have ensure that it is "Public", but it never comes up when sifting through the Assistants list.

**Describe the solution you'd like**

- I would like the ability to use Assistants that are private/belong to my user account.
- I would like to manipulate the following properties within `chatbot.new_conversation()`
  - ![image](https://github.com/Soulter/hugging-chat-api/assets/97307321/b1c550b8-9c2e-4ded-b046-fdc56b201aba)
  - I got there by clicking "edit" on the assistant 
  - ![image](https://github.com/Soulter/hugging-chat-api/assets/97307321/547bc6f0-e7b5-4183-bad3-78fd4b8a6b65)
- Even more specifically, the ability to add specific links to reference would be great!
  - ![image](https://github.com/Soulter/hugging-chat-api/assets/97307321/976d936d-1085-4c6b-a895-90076bc25e48)

**Describe alternatives you've considered**

I am currently working around this by providing the `system_prompt` parameter and it is working as intended. I know there is an exceptionally long (24576 chars) `system_prompt` length, but using the assistant seems like the more appropriate solution.

**Additional context**

Thanks for the help!

**Comment by Soulter** [comment]
Hello, you can try the solution below on this issue: https://github.com/Soulter/hugging-chat-api/issues/191

**Comment by Krovikan-Vamp** [comment]
✅Got it working! Had to make a work around and there were some caveats.

To have it work correctly I had to:

```python
chatbot.switch_llm(4) # switch to "Nous-Hermes-2-Mixtral-8x78-DPO" THIS WILL UPDATE AT HF DISCRETION
convo = chatbot.new_conversation(assistant='65f4ab39aa68a03835ed8177') # Create a new conversation using the assistant
response = chatbot.chat(my_query, conversation=convo) # Start a chat and explicitly state which conversation to use
```

This still creates a blank conversation that shows an error in the HC web UI each time it start.
