### ISSUE TITLE
ChatError's after 5-10 requests 

### ISSUE THREAD

**Issue by foolosopherr** [Soulter/hugging-chat-api#196]
I keep getting ChatError “You are sending too many messages. Try again later." immediately after 5-10 requests in 5 minutes. I know there is a daily limit of 500 requests, but are there additional limits (number of tokens per minute, number of requests per minute, etc.)? I don't get any errors using only the Chat-UI version, so maybe this is a bug.

<img width="354" alt="image" src="https://github.com/Soulter/hugging-chat-api/assets/70015183/66933bef-4079-46f8-8a98-75db41129fc3">

**Comment by Soulter** [comment]
Hi, the threshold of huggingchat is currently at about 5 messages per minute, and 500 messages per day, maybe you invoke chat function too many times at the same time unintentionally
