### ISSUE TITLE
What is the usual workflow ? Can it be also used for RAG applications ?

### ISSUE THREAD

**Issue by pmahan00** [Soulter/hugging-chat-api#198]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. I was a bit confused if there is a workflow for chatting . Lets say 
1. login
2. choose model
3. start chatting 

**Describe the solution you'd like**
For the second part , can we build a RAG solution on top of huggingface chat ? If so , how and that would be great. 
**Describe alternatives you've considered**
Nothing yet
**Additional context**

**Comment by Soulter** [comment]
Yes, the usual workflow is the same of you said. You can use RAG first, and put the retrieval result into your prompt and send them to huggingchat.
