### ISSUE TITLE
Override Parameters

### ISSUE THREAD

**Issue by normandmickey** [Soulter/hugging-chat-api#2]
Is there a way to override the following parameters?

"temperature": temperature,
                "top_p": top_p,
                "repetition_penalty": repetition_penalty,
                "top_k": top_k,
                "truncate": truncate,
                "watermark": False,
                "max_new_tokens": 1024,
                "stop": ["</s>"],
                "return_full_text": False,
                "stream": True,

**Comment by Soulter** [comment]
The new version `v0.0.4` supports to override the paratemers you said.

**Comment by normandmickey** [comment]
Thanks! I will check out this evening.
