### ISSUE TITLE
error when editing

### ISSUE THREAD

**Issue by kokofixcomputers** [Soulter/hugging-chat-api#201]
**Describe the bug**
When i edit a message through the huggingface website and try to send a message it produces:
Traceback (most recent call last):
  File "/Users/kokofixcomputers/Git/snakybot/main.py", line 78, in <module>
    chatbot.change_conversation(ai_instance)
  File "/Users/kokofixcomputers/Library/Python/3.11/lib/python/site-packages/hugchat/hugchat.py", line 333, in change_conversation
    self.get_conversation_info(local_conversation)
  File "/Users/kokofixcomputers/Library/Python/3.11/lib/python/site-packages/hugchat/hugchat.py", line 608, in get_conversation_info
    created_at=datetime.datetime.strptime(data[_node_meta["createdAt"]][1], "%Y-%m-%dT%H:%M:%S.%fZ").timestamp(),
                                               ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'createdAt'

i used query_result = chatbot.chat(text) to send message. it also have the same problem when switching the conversation to a conversation that has messages edited and regenerated

**To Reproduce**
How can we reproduce this bug via code? If possible, please provide the portion of your code showcasing this bug.

**Expected behavior**


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
What Operating System are you using? MacOS
What Python version are you using? Python 3.11.3
What version of hugchat are you using? 0.4.2

**Comment by Soulter** [comment]
fixed

**Comment by kokofixcomputers** [comment]
> fixed, thanks for your feedback

thanks!
