### ISSUE TITLE
Logging in getting 401 error.

### ISSUE THREAD

**Issue by FBRDCYB3R** [Soulter/hugging-chat-api#203]
When running the app via the CLI with 

`python -m hugchat.cli -u <email>`

it just gives me this error: Exception: Failed to get remote LLMs with status code: 401

I have a token on huggingface and everything. Does anyone know how to fix this issue

**Comment by lethxrgy1** [comment]
Same error today

**Comment by Whitelisted1** [comment]
Are you logging in with a password or with stored cookies? I was having an issue on my account until I regenerated my cookie.

**Comment by Whitelisted1** [comment]
Nevermind, after a quick test it seems that I am able to reproduce the issue

**Comment by Whitelisted1** [comment]
Make sure that you delete your old cookies folder. I was having the same issue until I did so. 

Now, though, I am getting a different error:
```bash
-------HuggingChat-------
Official Site: https://huggingface.co/chat
1. AI is an area of active research with known problems such as biased generation and misinformation.
2. Do not use this application for high-stakes decisions or advice.
Continuing to use means that you accept the above point(s)

Logging in...
Signed in as <REDACTED> .. attempting to login
Login successfully! 🎉
You can input `/help` to open the command menu.

Traceback (most recent call last):
  File "c:\...\hugging-chat-api\test.py", line 19, in <module>
    cli.cli()
  File "c:\...\hugging-chat-api\src\hugchat\cli.py", line 267, in cli
    target_id = conversation_dict[2]
KeyError: 2
```

**Comment by Whitelisted1** [comment]
Make sure that you delete your old cookies folder. I was having the same issue until I did so.

**Comment by FBRDCYB3R** [comment]
How do I clear my cookies folder?

**Comment by Soulter** [comment]
> How do I clear my cookies folder?

The cookies folder stores in the directory where you executed this command and called `usercookies`. You can delete this folder and try again.

**Comment by AnaghaAMT** [comment]
Can anyone tell me the validity of each token?
