### ISSUE TITLE
May I ask how to single request add history?

### ISSUE THREAD

**Issue by MonolithFoundation** [Soulter/hugging-chat-api#205]
May I ask how to single request add history? 

This really needed

**Comment by Soulter** [comment]
Hello, it doesn't support to edit history for now. I'll work for it. But it can add system prompt.

**Comment by MonolithFoundation** [comment]
Thank you for the reply ， It would be very perfect if the can sending history together，Since we mostly using are need history



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/04/2024 11:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Soulter/hugging-chat-api] May I ask how to single request add history? (Issue #205) |

Hello, it doesn't support to edit history for now. I'll work for it. But it can add system prompt.

**Comment by MonolithFoundation** [comment]
@Soulter  hi, any updates?

**Comment by Soulter** [comment]
i'm so sorry that I can't find any way to add history in a conversation. The history are saved in it server and cannot be edited. But it supports to edit previous message and I just implemented it and for is waiting for the next release.

**Comment by MonolithFoundation** [comment]
No, I. mean, if this is a lib, then, it should make users make a request can added a history, otherwise it can only do single turn conversation.
