### ISSUE TITLE
"No authorize url found, please check your email or password."

### ISSUE THREAD

**Issue by MexicanBauss** [Soulter/hugging-chat-api#210]
I have been using this API for a while now to access the HuggingFace models, and it has worked fantasticly well until recently. 
Suddenly, I'm unable to login from the API, and I have not changed anything. I'm getting the error: `"No authorize url found, please check your email or password.". `

Has the HuggingChat site changed recently were they would require extra authorization?

**Comment by edygordo** [comment]
I am facing the same issue, although i get an email from hugging face saying that you have logged in through the credentials. Strange!
