### ISSUE TITLE
web search results giving buggy response

### ISSUE THREAD

**Issue by mian312** [Soulter/hugging-chat-api#212]
**Describe the bug**
The model is working fine, but not when the web search is enabled.
until the web_search is enabled false or not mentioned the response is coming, but the point when the web search is enabled the response is buggy. It probably throws a bunch of tokens though I am not a expertise of this field so I cannot say how the response it gives.

**Issue Code**
```
assistant = chatbot.search_assistant(assistant_name="Real Human")
chatbot.new_conversation(assistant=assistant, switch_to=True)

query_result = chatbot.query("hi", web_search=True)
print(query_result)
```

**Expected behavior**
It should give response like : 
"Hello! How are you feeling today?"
as it gives response when web_search=False

**Screenshots**
![Screenshot 2024-05-15 173245](https://github.com/Soulter/hugging-chat-api/assets/102272538/876029a7-050f-4c12-b1b1-af1e7196e102)
![Screenshot 2024-05-15 173245 01](https://github.com/Soulter/hugging-chat-api/assets/102272538/ea31b8dc-3eed-430a-88f1-fbac0316086e)
![Screenshot 2024-05-15 173245 02](https://github.com/Soulter/hugging-chat-api/assets/102272538/f29994dd-9468-4686-a8a3-5eb18f76dbf1)

**Comment by TribSTox** [comment]
D'accord, je vais reformuler la réponse en anglais et sans inclure de nom :

---

Hi,

I confirm the issue mentioned in the latest message. Upon analyzing the returned JSON, it's clear that the `hostname` property no longer exists. Here's an example of the returned JSON object:

```json
{
  "title": "M-theory",
  "link": "https://en.wikipedia.org/wiki/M-theory",
  "snippet": "A theory of strings that incorporates the idea of supersymmetry is called a superstring theory. There are several different versions of superstring theory ...",
  "position": 1
  // other properties...
}
```

As you can see, there is no `hostname` property, which explains the error. Thank you for the proposed fix.

Best regards,

**Comment by Mrxyy** [comment]
I hope this PR will be merged.

**Comment by Soulter** [comment]
> Hi,
> 
> I confirm the issue mentioned in the latest message. Upon analyzing the returned JSON, it's clear that the `hostname` property no longer exists. Here's an example of the returned JSON object:
> 
> ```json
> {
>   "title": "M-theory",
>   "link": "https://en.wikipedia.org/wiki/M-theory",
>   "snippet": "A theory of strings that incorporates the idea of supersymmetry is called a superstring theory. There are several different versions of superstring theory ...",
>   "position": 1
>   // other properties...
> }
> ```
> 
> As you can see, there is no `hostname` property, which explains the error. Thank you for the proposed fix.
> 
> Committed fix can be reviewed here: [master...TribSTox:hugging-chat-api:patch-1](https://github.com/Soulter/hugging-chat-api/compare/master...TribSTox:hugging-chat-api:patch-1)
> 
> Best regards,

Thanks you for your feedback, there was `hostname` property before, it should be huggingface deleted it. You can create a PR and I'll merge it.

**Comment by TribSTox** [comment]
Hi,
I have created the PR as recommended.

Best regards,

**Comment by Soulter** [comment]
> Hi, I have created the PR as recommended.
> 
> Best regards,

Hello, I have merged the PR and released a new version. Thanks

**Comment by Soulter** [comment]
> > Hi, I have created the PR as recommended.
> > Best regards,
> 
> Hello, I have merged the PR and released a new version. Thanks

You can use `pip install -U hugchat` to update.
