### ISSUE TITLE
Model Overload Error

### ISSUE THREAD

**Issue by Himanshu-369** [Soulter/hugging-chat-api#219]
I was just using the lightest "Phi-3" model and suddenly it gave Model overload Error. Used another id Still the same

`Traceback (most recent call last):
  File "/home/user/new/.venv/lib/python3.11/site-packages/hugchat/hugchat.py", line 738, in _stream_query
hugchat.exceptions.ChatError: Failed to parse response: {"type":"status","status":"error","message":"Model is overloaded"}`

From couple of days i was using this api it sometimes acts strange and like Today the **"web_search "** function is not working properly, i set it to True and it sometimes switches off while giving the responses.

**Comment by Soulter** [comment]
That's a huggingface side problem, because too many people using this model and the server cannot keep up. You can change other models and try again.
