### ISSUE TITLE
ERROR: Non-JSON form requests need to have a referrer

### ISSUE THREAD

**Issue by tomjuggler** [Soulter/hugging-chat-api#22]
Python 3.10 on Manjaro Linux laptop. 
huggingchat updated to 0.0.6
added the cookies.json as per instructions, code is just the example code. 

full last line of message: 
`hugchat.py", line 92, in accept_ethics_modal
    raise Exception(f"Failed to accept ethics modal with status code {response.status_code}. {response.content.decode()}")
Exception: Failed to accept ethics modal with status code 403. Non-JSON form requests need to have a referer`

**Comment by ahmed3520** [comment]
same here. The error was occurring in the `accept_ethics_modal` method of the `ChatBot` class. To resolve this issue, I copied the code from the `hugchat.py` file into my own file and then commented out the lines in the `new_conversation` method that were calling the `accept_ethics_modal` method(lines `109` and `110`). This prevented the `accept_ethics_modal` method from being called and resolved the issue I was seeing.

**Comment by CCCBora** [comment]
I just met the same problem since they currently require log-in information. They just updated [README.md](https://github.com/Soulter/hugging-chat-api) and it says change `chatbot = hugchat.ChatBot()` to `chatbot = hugchat.ChatBot(cookie_path="cookies.json")`.

**Comment by JD-The-65th** [comment]
> I just met the same problem since they currently require log-in information. They just updated [README.md](https://github.com/Soulter/hugging-chat-api) and it says change `chatbot = hugchat.ChatBot()` to `chatbot = hugchat.ChatBot(cookie_path="cookies.json")`.

This is a totally different issue unrelated to this, even when this is changed, the issue mentioned before still occurs.

**Comment by CCCBora** [comment]
> > I just met the same problem since they currently require log-in information. They just updated [README.md](https://github.com/Soulter/hugging-chat-api) and it says change `chatbot = hugchat.ChatBot()` to `chatbot = hugchat.ChatBot(cookie_path="cookies.json")`.
> 
> This is a totally different issue unrelated to this, even when this is changed, the issue mentioned before still occurs.

I apologize for my understanding. Just ignore my comment.

**Comment by Soulter** [comment]
Fixed.
