### ISSUE TITLE
Nice work, can it add history support?

### ISSUE THREAD

**Issue by lucasjinreal** [Soulter/hugging-chat-api#221]
Nice work, can it add history support?

**Comment by Soulter** [comment]
Hello, hugchat has supported to record and retrieve histories. You can see the conversation history on huggingchat website or use this function(update to the latest version): 
```py
c = get_conversation_info(conversation=YOUR_CONVERSATION_ID)
print(c.history)
```

**Comment by lucasjinreal** [comment]
Hi, not get history, but sending history to the api.
