### ISSUE TITLE
Is it possible to continue a chat in the next session?

### ISSUE THREAD

**Issue by tkarrergit** [Soulter/hugging-chat-api#222]
Is it possible to continue a chat in the next session? It would be ideal if a conversation ID could be saved and used in the next session to resume the chat. How can I achieve this? Thank you very much for your assistance.

**Comment by YWaller** [comment]
Let me +1 this one. I also would like this functionality. I can't seem to, even though I'm saving the conversation id, get the bot to carry a conversation past one message. All my attempts using session stuff (flask) fail - get_conversation_from_id, etc.
