### ISSUE TITLE
Confusion with conversation names and conversation id's

### ISSUE THREAD

**Issue by lucasmelz** [Soulter/hugging-chat-api#3]
Hi! I was trying to make the AI talk to herself and I spotted a bug on this project! 
I was trying to use the chat.change_conversation(conversation_id) method to go from one conversation to another, the answer that the AI gave me in one conversation I would use to send to the AI in another conversation, in an eternal loop :D. Anyway, the method change_conversation(conversation_id) has an exception checking that doesn't make sense:
```
     def change_conversation(self, conversation_id: str) -> bool:
       if conversation_id not in self.conversation_list:
           raise Exception("Invalid conversation id. Please check conversation id list.")
        self.now_conversation = conversation_id
        return True
```
That if statement... The conversation_list contain the names (topics) of the conversations, not the id's. So it will always throw an exception because we need to use the id and not the conversation name to change to another conversation.

If I comment that if statement out, then everything works just fine. Btw, if anyone wants to test the AI talking to herself, just comment that if statement and try this code:
```
import asyncio
import hugchat
chatbot = hugchat.ChatBot()

async def firstResponse(text):
    return chatbot.chat(text)

async def fetchResponse(text, conversation_id):
    chatbot.change_conversation(conversation_id)
    return chatbot.chat(text)

async def main():
    # Start the first conversation
    conv_id1 = chatbot.new_conversation()
    temp = await fetchResponse("Hi, how are you?", conv_id1)
    print("-------------------------------------------------------------------------")
    print(f"Bot 1: {temp}")
    # Start the second conversation
    conv_id2 = chatbot.new_conversation()
    temp2 = await fetchResponse("Hello, what's up?", conv_id2)
    print("-------------------------------------------------------------------------")
    print(f"Bot 2: {temp2}")

    while True:
       temp = await fetchResponse(temp2, conv_id1)
       print("-------------------------------------------------------------------------")
       print(f"Bot 1: {temp}")
       temp2 = await fetchResponse(temp, conv_id2)
       print("-------------------------------------------------------------------------")
       print(f"Bot 2: {temp2}")

asyncio.run(main())
```

**Comment by lucasmelz** [comment]
I forked this repo with the code of my self-talking AI xD

**Comment by Soulter** [comment]
Thank you for your issue! That's a fatal and ridiculous bug indeed😂, I will fix it soon.

**Comment by lucasmelz** [comment]
You're welcome! Thank you for the API, it was very fun to play with it :)
