### ISSUE TITLE
When model is overloaded the program crashes

### ISSUE THREAD

**Issue by mak448a** [Soulter/hugging-chat-api#34]
When the api responds with the response `{"error":"Model is overloaded","error_type":"overloaded"}`, the program crashes. You should handle this with an if statement and perhaps try sending the request again. This is at line 260 of hugchat.py in the latest pypi version.

**Comment by mak448a** [comment]
The program crashes when `obj = json.loads(res[1:-1])` is called because it is probably expecting a reply from the model, so when `res = line.decode("utf-8")` is called, it crashes.

**Comment by RockChinQ** [comment]
Fixed, please wait for the next release.

**Comment by RockChinQ** [comment]
update `hugchat` with `pip install hugchat --upgrade`

then simply catch this error with

```python
from hugchat.exceptions import *

...

try:
    print(chatbot.chat("Hello"))
except ModelOverloadedError:
    print("model overloaded error caught.")
```

**Comment by mak448a** [comment]
Got it, thanks
