### ISSUE TITLE
HugChat api has amnesia

### ISSUE THREAD

**Issue by luiskawaiineko** [Soulter/hugging-chat-api#36]
I tried something. I made a code and then in my own implementation I told him in same conversation "Hi. My name is Luis" and he answers me something like "Hi Luis. I'm here to help." The problem is that next to that message I ask him "I just told you my name. What is my name?" and he says "I don't remember you telling me your name before" or something like that. It happens same with HugChat cli. But when I do this same in the HuggingFace website, I make the same conversation and he tells me "As you stated before, your name seems to be Luis"

**Comment by RockChinQ** [comment]
Same topic as #5 , tracking this feature there.
