### ISSUE TITLE
 Failed to chat. Status code: 429

### ISSUE THREAD

**Issue by jihanyang** [Soulter/hugging-chat-api#4]
Thanks for you nice work. I meet up with such error, may I know what should I do to solve it?
```
    raise Exception(f"Failed to chat. Status code: {resp.status_code}")
Exception: Failed to chat. Status code: 429
```

**Comment by Soulter** [comment]
Code 429 is a `Too Many Requests` error in HTTP, maybe you requested chat too fast in a short period of time.

**Comment by jihanyang** [comment]
Thank you so much
