### ISSUE TITLE
Search Web functionality

### ISSUE THREAD

**Issue by marcelosousa-utexas** [Soulter/hugging-chat-api#41]
In HuggingChat web browser version there is a buttton to enable web search. 
How can I enable this using hugging-chat-api? 
Thank you.

**Comment by nielshelsoe** [comment]
as i understand the URL should be modified as follows if you want to use web search:  

`https://huggingface.co/chat/conversation/<id>/web-search?prompt=<promt>` 

I could maybe just be a `bool` value on the `chat` func?

But as Ogios points out it has a very bad performance. I have just tried to be using it and it keeps saying that it does not git any hist on Google

**Comment by Soulter** [comment]
Hi! Version 0.3.0 supported the feature. View README.md to get the usage.
