### ISSUE TITLE
No csrf found

### ISSUE THREAD

**Issue by IntelligenzaArtificiale** [Soulter/hugging-chat-api#45]
Hi super guys,
your project is really cool.

I'm working on a plugin-on-top version of chat that has your library as its core LLM.

After much development (and therefore many logins) I started getting this error: 

```
[cookies = sign.login()
   File "/home/alino/.local/lib/python3.10/site-packages/hugchat/login.py", line 122, in login
     if self.grantAuth(location):
   File "/home/alino/.local/lib/python3.10/site-packages/hugchat/login.py", line 103, in grantAuth
     raise Exception("No csrf found!")
Exception: No csrf found!]
```

Do you know how I can fix it?
I thought it was due to frequent use, but I also tried creating new accounts for testing and now I always get that error : Exception: No csrf found!

this is my requirement :
```
beautifulsoup4==4.12.2
docx2txt==0.8
duckduckgo_search==3.8.3
hugchat==0.0.7.1
langchain==0.0.219
pandas==2.0.1
pdfplumber==0.9.0
pydub==0.25.1
requests
sketch==0.4.2
SpeechRecognition==3.8.1
streamlit==1.24.0
streamlit_extras==0.2.7
youtube_search_python==1.6.6
youtube_transcript_api==0.6.1
chromadb==0.3.26
ffmpeg-python
ffprobe
```

for view live error go to : [https://free-personal-ai-assistant.streamlit.app/](https://free-personal-ai-assistant.streamlit.app/)

I would really like it if you take a look at my project : [https://github.com/IntelligenzaArtificiale/Free-personal-AI-Assistant](https://github.com/IntelligenzaArtificiale/Free-personal-AI-Assistant). It's very easy to run, install library and type `streamlit run streamlit_app.py`

**Comment by Jagadeesha89** [comment]
I build web app chatbot using Hugchat, since from last one hour i am getting same error
![Screenshot_2023_0630_212329](https://github.com/Soulter/hugging-chat-api/assets/119878086/3061b2d4-8bd1-48dc-bd0d-602153ea514c)

**Comment by ogios** [comment]
After login, huggingchat needs a auth from huggingface to create a hf cookie that has the authorization to chat
But it's late night(0:30) now, i will try to fix it tomorrow.
By the way, it works just fine on my machine:
![IMG_20230701_003722.jpg](https://github.com/Soulter/hugging-chat-api/assets/96933655/31247f7d-cb3b-4bea-80dc-a146572e57ca)

**Comment by ogios** [comment]
Checked, it used to have a page for you to manually grant auth, but now it's automatically done.
So the `re` can not fetch the auth URL anymore.

**Comment by ogios** [comment]
After several tests, I come to the conclusion that perhaps the auth of one account has an expiration time now, which doesn't require one account to grant auth to it every time you use it.
I tested it using the email I seldomly used, it requires me to manually grant auth to the hugging chat, but after that, it's not required with another browser. 
I have this updated in my another [repo](https://github.com/ogios/huggingchat-api) for the test, and I'm going to do a  Pull Request to this repo too.
