### ISSUE TITLE
Error No csrf found 

### ISSUE THREAD

**Issue by Jagadeesha89** [Soulter/hugging-chat-api#46]
I am getting error No csrf found, i have developed web app chat bot using Hugchat, since from one hour i m getting error.
![Screenshot_2023_0630_212329](https://github.com/Soulter/hugging-chat-api/assets/119878086/7217a7d4-73a7-4c25-8351-e8ab181266f2)

**Comment by ogios** [comment]
https://github.com/Soulter/hugging-chat-api/issues/45#issuecomment-1614905068

**Comment by ogios** [comment]
https://github.com/Soulter/hugging-chat-api/issues/45#issuecomment-1615447920

**Comment by Soulter** [comment]
Published a new version `0.0.8`.
Use following command to update it.
```bash
pip3 install -upgrade hugchat
```

Thanks to @ogios !

**Comment by Jagadeesha89** [comment]
Its working now

Thanks to @ogios and @Soulter for ur great support
