### ISSUE TITLE
How to grant authorization to huggingchat on Huggingface?

### ISSUE THREAD

**Issue by rukshar69** [Soulter/hugging-chat-api#48]
In your README, you've mentioned `# Log in to huggingface and grant authorization to huggingchat`. How do I grant authorization to huggingchat on Huggingface?

**Comment by ogios** [comment]
is there any error occurred?
Authorization is automatically granted by the script so you don't have to worry about that

**Comment by rukshar69** [comment]
So, I only have to input my email and password?

**Comment by ogios** [comment]
> So, I only have to input my email and password? 

yes
