### ISSUE TITLE
getting "no csrf found" error frequently

### ISSUE THREAD

**Issue by anzarwani** [Soulter/hugging-chat-api#50]
I am running a streamlit app and credentials are well placed in secrets.toml file. The app used to work fine but in the last run I got the below error.

`File "/home/appuser/venv/lib/python3.9/site-packages/hugchat/login.py", line 102, in grantAuth
    raise Exception("No csrf found!")`

link to the project : [BookBot](https://github.com/anzarwani/hugging-chat-book-bot/blob/main/hugging-chat-book-bot-main/app.py)

**Comment by ogios** [comment]
the package just had an update 2 days ago(0.0.8),  you still get the error after update?

**Comment by anzarwani** [comment]
I updated the package and didn't get the csrf error anymore but now I am getting below error.

`AttributeError: 'Login' object has no attribute 'saveCookies'`

I will need to check this. Thank you!

**Comment by ogios** [comment]
https://github.com/Soulter/hugging-chat-api/pull/44

the save and load funtions' name was changed and support customized path

**Comment by anzarwani** [comment]
@ogios It is working now. Thank you.

I think the readme.md needs to be updated to reflect the recent changes. It still has old function names.
