### ISSUE TITLE
Addition of CSRF token

### ISSUE THREAD

**Issue by AnaghaAMT** [Soulter/hugging-chat-api#54]
"Hi, it is giving a CSRF token not found error. How can I add the CSRF token in the request? This issue is not 
allowing me from logging in and obtaining the cookie.

**Comment by ogios** [comment]
![Screenshot_2023-07-17-18-23-19-88_61c78dc80ee02b53007c815fefe993e3.jpg](https://github.com/Soulter/hugging-chat-api/assets/96933655/56aa6a47-be37-4ffe-b3cb-aedc0286910c)

no error found, have you update the package?

**Comment by AnaghaAMT** [comment]
yes,i have updated the package to hugchat==0.0.7.1.when running after giving the login credentials i am getting like given below:
if self.grantAuth(location):
 raise Exception("No csrf found!")
Exception: No csrf found!

**Comment by ogios** [comment]
well actually, the latest version is 0.0.8 which fixed this issue:
https://github.com/Soulter/hugging-chat-api/releases/tag/v0.0.8

**Comment by AnaghaAMT** [comment]
ok....thanks....!!

**Comment by ogios** [comment]
my pleasure
