### ISSUE TITLE
Continue the same chat

### ISSUE THREAD

**Issue by ClayArrobakker** [Soulter/hugging-chat-api#55]
Is there any way I can converse in the same chat instead of having each request creating a new chat? Not only does it not allow context, but also is just annoying. Not really an issue per say, but nonetheless annoying.

**Comment by ogios** [comment]
u can try [this](https://github.com/ogios/huggingchat-api)
but may need to change some code u written

**Comment by ClayArrobakker** [comment]
> u can try [this](https://github.com/ogios/huggingchat-api) but may need to change some code u written

Thank you! I'll look into it.
