### ISSUE TITLE
Feature Request: Ability to select model

### ISSUE THREAD

**Issue by linux-leo** [Soulter/hugging-chat-api#56]
The Ability to select between meta-llama/Llama-2-70b-chat-hf and OpenAssistant/oasst-sft-6-llama-30b would be nice.

**Comment by Soulter** [comment]
Implemented. Wait me to publish a new version.

**Comment by Soulter** [comment]
```bash
pip3 install hugchat --upgrade
```

You can invoke `switch_llm(1)` to change model to meta-llama/Llama-2-70b-chat-hf ,   `switch_llm(0)` to OpenAssistant/oasst-sft-6-llama-30b


Details: 
```

switch_llm(self, to: int) -> bool:
    '''
    Attempts to change current conversation's Large Language Model.
    Requires an index to indicate the model you want to switch.
    For now, 0 is `OpenAssistant/oasst-sft-6-llama-30b-xor`, 1 is `meta-llama/Llama-2-70b-chat-hf` :)
    
    * llm 1 is the latest LLM.
    * REMEMBER: For flexibility, the effect of switch just limited to *current conversation*. You can manually switch llm when you change a conversasion.
    '''

```

**Comment by Soulter** [comment]
> Can anyone give an example of how to switch LLM? In Inference Code

Hi! Here are some codes may help you.
```python

from hugchat import hugchat
from hugchat.login import Login

# Log in to huggingface and grant authorization to huggingchat
sign = Login(email, passwd)
cookies = sign.login()

# Save cookies to the local directory
cookie_path_dir = "./cookies_snapshot"
sign.saveCookiesToDir(cookie_path_dir)

# Create a ChatBot
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"
print(chatbot.chat("Hello"))

# Create a new conversation
id = chatbot.new_conversation()
chatbot.change_conversation(id)

# switch LLM
chatbot.switch_llm(0) # switch to OpenAssistant/oasst-sft-6-llama-30b-xor
chatbot.switch_llm(1) # switch to meta-llama/Llama-2-70b-chat-hf
```

**Comment by MariosMarkakis** [comment]
Can someone help with providing the mapping of the below models currently available in hugging chat so that i can use switch_llm() to query them?

meta-llama/Llama-2-70b-chat-hf
[codellama/CodeLlama-34b-Instruct-hf]
[tiiuae/falcon-180B-chat]
[mistralai/Mistral-7B-Instruct-v0.2]
[openchat/openchat_3.5]
[mistralai/Mixtral-8x7B-Instruct-v0.1]

**Comment by Whitelisted1** [comment]
> Can someone help with providing the mapping of the below models currently available in hugging chat so that i can use switch_llm() to query them?
> 
> meta-llama/Llama-2-70b-chat-hf [codellama/CodeLlama-34b-Instruct-hf] [tiiuae/falcon-180B-chat] [mistralai/Mistral-7B-Instruct-v0.2] [openchat/openchat_3.5] [mistralai/Mixtral-8x7B-Instruct-v0.1]

You are able to use `chatbot.get_available_llm_models()` to get a list of available models.

**Comment by pochieh515** [comment]
I also have the same issue with chatbot.switch_llm().
I wanna change the model from 'meta-llama/Llama-2-70b-chat-hf' to 'mistralai/Mistral-7B-Instruct-v0.2' so that I use chatbot.switch_llm(3) but it still is 'meta-llama/Llama-2-70b-chat-hf'. Is there have any suggest?

**Comment by Whitelisted1** [comment]
> I also have the same issue with chatbot.switch_llm(). I wanna change the model from 'meta-llama/Llama-2-70b-chat-hf' to 'mistralai/Mistral-7B-Instruct-v0.2' so that I use chatbot.switch_llm(3) but it still is 'meta-llama/Llama-2-70b-chat-hf'. Is there have any suggest?

Try creating a new conversation after you switch to the Mistral model with `chatbot.new_conversation()`

**Comment by pochieh515** [comment]
Thanks for your response. When I use 'chatbot = hugchat.ChatBot(cookie_path="...", default_llm=3)' or create a new conversation after switch model it also show as below:
![螢幕擷取畫面 2023-12-25 112239](https://github.com/Soulter/hugging-chat-api/assets/39297339/93feaaa2-aaf1-4d40-87bd-94df05b4b1fb)
Is there have any suggest?

**Comment by Whitelisted1** [comment]
Did you replace the cookie_path parameter with the actual path to your cookies file? Sorry if I was unclear before

**Comment by Whitelisted1** [comment]
I'm not having the same error. Would you please show a copy of your code, if possible?

**Comment by pochieh515** [comment]
Thanks for your response. You can see the picture as below:
![螢幕擷取畫面 2023-12-25 113326](https://github.com/Soulter/hugging-chat-api/assets/39297339/9c9bd7f3-3b03-4516-acaf-7f8a25c5eb1f)

**Comment by Whitelisted1** [comment]
After some testing it seems that the error comes from the fact that we are trying to create a conversation with the model `mistralai/Mistral-7B-Instruct-v0.1`, which doesn't show up on the [HuggingChat GUI](https://huggingface.co/chat). I'll create a new issue on this topic.

**Comment by Whitelisted1** [comment]
> Thanks for your response. You can see the picture as below: ![螢幕擷取畫面 2023-12-25 113326](https://private-user-images.githubusercontent.com/39297339/292705312-9c9bd7f3-3b03-4516-acaf-7f8a25c5eb1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjU0NzksIm5iZiI6MTcwMzYyNTE3OSwicGF0aCI6Ii8zOTI5NzMzOS8yOTI3MDUzMTItOWM5YmQ3ZjMtM2IwMy00NTE2LWFjYWYtN2Y4YTI1YzVlYjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NzRjZWU4MGEyNDg1MGIzOWM5ZDVhYTA1ZTg5ZmUzY2NiYzNjM2ZlNTFhNDFiNmEyMWQyZjExNTMyODQ5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89RtEMOCfY8Ql99KHd-lsatzPlDsZxEO7e8--xOEho8)

You should still be able to use other models by changing the default_llm index to something other than 3
