### ISSUE TITLE
ERROR: requests.exceptions.ConnectionError when login

### ISSUE THREAD

**Issue by yuhuangyue** [Soulter/hugging-chat-api#59]
when I run `cookies = sign.login()`

it comes out 
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by Soulter** [comment]
It may only be a temporary network malfunction. Just try again.

**Comment by yuhuangyue** [comment]
I have try a lot, still occurs this error.
Is there anything wrong with VPN?
