### ISSUE TITLE
API Response Cut Off: Inconsistent Results with HuggingChat

### ISSUE THREAD

**Issue by MUZAMMILPERVAIZ** [Soulter/hugging-chat-api#65]
Hi,
I have tested this API, I used the same prompt for requesting this API and Huggingchat, The response from this API was very limited and cut off, I tried increasing max_new_tokens but still, the generated result was short and incomplete, 

The same prompt on hugging chat gave a lengthy complete result.

Can anyone help?

**Comment by Soulter** [comment]
My Test:

`HuggingChat` Final Response:
<img width="483" alt="image" src="https://github.com/Soulter/hugging-chat-api/assets/37870767/06a26049-c9a6-4824-b256-7d3a6c9b2bbd">


`chatbot.chat()` return:

<img width="481" alt="image" src="https://github.com/Soulter/hugging-chat-api/assets/37870767/47ed2fb8-ba75-4648-ada4-5af3a491b50c">

**Comment by MUZAMMILPERVAIZ** [comment]
Code:
![image](https://github.com/Soulter/hugging-chat-api/assets/69303067/7e0e7936-aef1-4500-a521-bd20a89a0a65)

Result:
![image](https://github.com/Soulter/hugging-chat-api/assets/69303067/cdacd4ee-e653-4c33-ac39-eaf6c150f145)

**Comment by MUZAMMILPERVAIZ** [comment]
The result was not complete

**Comment by Soulter** [comment]
> The result was not complete

What's your hugchat version?

```
pip3 show hugchat
```

**Comment by MUZAMMILPERVAIZ** [comment]
hugchat-0.1.0

**Comment by Soulter** [comment]
Try to execute:
```bash
pip3 install hugchat==0.2.0
```
and retry

**Comment by MUZAMMILPERVAIZ** [comment]
It works Thanks, Is it the latest version?

**Comment by Soulter** [comment]
Yes, and the version implement context

> It works Thanks, Is it the latest version?
