### ISSUE TITLE
Can't sign in, even with proper credentials

### ISSUE THREAD

**Issue by ramdastejas** [Soulter/hugging-chat-api#69]
Hi, thanks a lot for the api! no mattter how many times i try to sign in, it says:

Traceback (most recent call last):

  Cell In[35], line 6
    cookies = sign.login()

  File ~\AppData\Local\anaconda3\Lib\site-packages\hugchat\login.py:125 in login
    self.SigninWithEmail()

  File ~\AppData\Local\anaconda3\Lib\site-packages\hugchat\login.py:70 in SigninWithEmail
    raise Exception("wrong username or password")

Exception: wrong username or password

I know for certain that i am typing the correct credentials. what to do?

**Comment by Soulter** [comment]
Hi, I can't detect the specific problem is, and it works well in my PC.

![image](https://github.com/Soulter/hugging-chat-api/assets/37870767/1370c87a-3356-4947-994e-0415624f4e26)

**Comment by ramdastejas** [comment]
It worked thanks! - the problem was that I had not confirmed my email.
