### ISSUE TITLE
Language problem?

### ISSUE THREAD

**Issue by stevessschen** [Soulter/hugging-chat-api#70]
I asked question in Chinese. But hugging chat api replied in English? 

But https://huggingface.co/chat/ worked fine! => I ask question in Chinese, and it also reply in Chinese.

Please help?!

**Comment by ogios** [comment]
有截图吗？
我这里使用的时候没有见过它输出中文，最多只出来几个用来解释和翻译的中文字，主要说的都是英文，所以我之前才做了一个接入有道翻译的版本。
或许是我不会引导它输出中文

**Comment by stevessschen** [comment]
All right. In https://huggingface.co/chat/ , I asked question in Chinese, it replied in English. And I asked again by saying "Please reply in Chinese." It did output the Chinese.

![image](https://github.com/Soulter/hugging-chat-api/assets/36218346/d4595385-5bc6-42fc-85b7-9d09d4b08a40)

![image](https://github.com/Soulter/hugging-chat-api/assets/36218346/19a3aa32-0f0c-4f6b-9a67-9cc276d83ce3)

**Comment by stevessschen** [comment]
But my problem still existed!! => I asked question in Chinese. But hugging chat api replied in English? => Because "hugging chat api" treated every prompt as a new chat causing the 2nd prompt was not able to link back to 1st prompt. So, the 2nd prompt "Please reply in Chinese." won't work since it's new chat.

Suggesting solution: Can "hugging chat api" allow us to have the same chat?

@ogios Please help and see my codes here: https://github.com/stevessschen/hugchat/blob/master/streamlit_app.py

**Comment by ogios** [comment]
> But my problem still existed!! => I asked question in Chinese. But hugging chat api replied in English? => Because "hugging chat api" treated every prompt as a new chat causing the 2nd prompt was not able to link back to 1st prompt. So, the 2nd prompt "Please reply in Chinese." won't work since it's new chat.

i dont think it's about ur code, have u updated? 
i saw that in `0.2.0` they fixed this old problem:
![image](https://github.com/Soulter/hugging-chat-api/assets/96933655/af1b9740-a5d6-4983-8bd3-79200ee36a15)

still have it?
