### ISSUE TITLE
System Prompt Edit Feature

### ISSUE THREAD

**Issue by WizardGato** [Soulter/hugging-chat-api#77]
I may have missed it but is there a way to add and edit the system prompt for the models? If not, it would be a great implementation that could really even more functionality to this!

**Comment by ogios** [comment]
Maybe you can add it to the prompt manually:
```
System: blablabla\nUser:your text\nFalcon:
```

**Comment by IntelligenzaArtificiale** [comment]
I am working to make hugchat api 100% compatible with langchain . look [this🤗](https://github.com/IntelligenzaArtificiale/hugging-chat-api-LLM-custom-Wrapper/tree/main#langchain-compatibility-100-)

**Comment by Soulter** [comment]
The feature has been implemented by @Whitelisted1. https://github.com/Soulter/hugging-chat-api/pull/105
