### ISSUE TITLE
Noticeable latency between model generation and API response

### ISSUE THREAD

**Issue by axplast** [Soulter/hugging-chat-api#82]
Hello! For some reason, there is a noticeable ~30 seconds latency between model finishing generation of it's response on a website and the text being send through API. Couldn't try it with streaming as it doesn't work for me at all though.

Is this a problem on my side? Or is it how it should actually work?

Thanks in advance!

**Comment by Sumandora** [comment]
Fixed by my PR
https://github.com/Soulter/hugging-chat-api/pull/81

**Comment by Soulter** [comment]
> Fixed by my PR #81

Updated. v0.2.7. Thanks!
