### ISSUE TITLE
[Function Request] Web Search support

### ISSUE THREAD

**Issue by Soulter** [Soulter/hugging-chat-api#85]

**Comment by ogios** [comment]
the thing is that the old api is deleted, thus you just have to pass `web_search=true` in the request body

the search process and the tokens are with in the same response, type is `webSearch`

you can check it here:   https://github.com/ogios/huggingchat-api/blob/main/hugchat_api/core/Chatflow.py#L101

**Comment by Soulter** [comment]
![image](https://github.com/Soulter/hugging-chat-api/assets/37870767/345f20d2-99a0-42f8-bd74-f99f3859d074)

**Comment by Soulter** [comment]
Hey everyone the version 0.3.0 published and support web search now. https://github.com/Soulter/hugging-chat-api/releases/tag/v0.3.0
