### ISSUE TITLE
Time Error

### ISSUE THREAD

**Issue by AravindRohit** [Soulter/hugging-chat-api#86]
Now, I am getting Responses for Hug Chat but it gives many time using same parameters in previous version it gives fast within 10 seconds but now it is taking 45 - 50 seconds

**Comment by ogios** [comment]
From what i experienced, the connection some times needs to be cut off manually.
i'm using aiohttp. Maybe it's something related to aiohttp itself but literally every request here will be end up with `Response payload is not completed`, thus waiting for the timeout.
I have to close the connection myself

**Comment by AravindRohit** [comment]
> From what i experienced, the connection some times needs to be cut off manually. i'm using aiohttp. Maybe it's something related to aiohttp itself but literally every request here will be end up with `Response payload is not completed`, thus waiting for the timeout. I have to close the connection myself

how can we reduce the time in before version it is came fast but now is not coming fast

**Comment by ogios** [comment]
> how can we reduce the time in before version it is came fast but now is not coming fast

what i did was just to call res.close() when detected `{"type":"finalAnswer"`
you can change it in `query` function located in `hugchat.py` file
no need to worry about the json parse error since `"` will be transfered to `\"` in json, but still, it may be unstable i can't be sure about that.

**Comment by IttiS46** [comment]
I am having the same issue. The waiting time is now significantly longer.

**Comment by AravindRohit** [comment]
> I am having the same issue. The waiting time is now significantly longer.

how can we reduce it

**Comment by RockChinQ** [comment]
Provide some cases please, so that we can determine such issue.

**Comment by IttiS46** [comment]
```
# %%
from hugchat import hugchat
from hugchat.login import Login
import os

from env import PROXIES

os.environ['http_proxy'] = PROXIES['http']
os.environ['https_proxy'] = PROXIES['https']

sign = Login('username', 'password')
cookie_path_dir = "./tmp"

try:
    cookies = sign.loadCookiesFromDir(cookie_path_dir)
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
except:
    cookies = sign.login()
    sign.saveCookiesToDir(cookie_path_dir)
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

# %%
prompt = 'tell me a joke'
resp = chatbot.chat(prompt)
print(resp)
```

These are my codes. The first part for login and initialization takes about 3.5s but the second part alone now takes about 35s. Currently I am running hugchat==0.3.1 with python 3.9.12

**Comment by AravindRohit** [comment]
def chatbot_response(email, passwd, input_text):
    # Try to load cookies from the fixed directory
    try:
        sign = Login(email, None)
        cookies = sign.loadCookiesFromDir(COOKIE_PATH_DIR)
    except Exception as e:
        # If loading cookies fails, perform a new login
        sign = Login(email, passwd)
        cookies = sign.login()
        sign.saveCookiesToDir(COOKIE_PATH_DIR)

    # Create a ChatBot
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

    # Create a new conversation
    conversation_id = chatbot.new_conversation()

    # Set the current conversation context
    chatbot.change_conversation(conversation_id)

    # Send the predefined input text to the chatbot
    response_dict = chatbot.query(
        text=input_text,
        temperature=0.2,
        max_new_tokens=1024,  # Experiment with a lower value
        top_k=10,  # Experiment with lower values
        top_p=0.7,  # Experiment with lower values
        use_cache=True,  # Enable response caching
        repetition_penalty=1.0,
        retry_count=2,  # Set the retry_count to a lower value, e.g., 2
        stream=False  # Disable streaming to get the entire response at once
    )

    # End the conversation (optional)
    chatbot.new_conversation()

    # Extract 'text' from the response dictionary
    if 'text' in response_dict:
        response_text = response_dict['text']
    else:
        response_text = "No 'text' field found in the response dictionary."

    # Ensure response is 2 to 3 sentences
    sentences = response_text.split('.')
    response_text = '. '.join(sentences[:3])

    # Ensure response ends with a full stop
    if not response_text.endswith('.'):
            response_text += '.'

    return response_text



> ```
> # %%
> from hugchat import hugchat
> from hugchat.login import Login
> import os
> 
> from env import PROXIES
> 
> os.environ['http_proxy'] = PROXIES['http']
> os.environ['https_proxy'] = PROXIES['https']
> 
> sign = Login('username', 'password')
> cookie_path_dir = "./tmp"
> 
> try:
>     cookies = sign.loadCookiesFromDir(cookie_path_dir)
>     chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
> except:
>     cookies = sign.login()
>     sign.saveCookiesToDir(cookie_path_dir)
>     chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
> 
> # %%
> prompt = 'tell me a joke'
> resp = chatbot.chat(prompt)
> print(resp)
> ```
> 
> These are my codes. The first part for login and initialization takes about 3.5s but the second part alone now takes about 35s. Currently I am running hugchat==0.3.1 with python 3.9.12

**Comment by AravindRohit** [comment]
> ```
> # %%
> from hugchat import hugchat
> from hugchat.login import Login
> import os
> 
> from env import PROXIES
> 
> os.environ['http_proxy'] = PROXIES['http']
> os.environ['https_proxy'] = PROXIES['https']
> 
> sign = Login('username', 'password')
> cookie_path_dir = "./tmp"
> 
> try:
>     cookies = sign.loadCookiesFromDir(cookie_path_dir)
>     chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
> except:
>     cookies = sign.login()
>     sign.saveCookiesToDir(cookie_path_dir)
>     chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
> 
> # %%
> prompt = 'tell me a joke'
> resp = chatbot.chat(prompt)
> print(resp)
> ```
> 
> These are my codes. The first part for login and initialization takes about 3.5s but the second part alone now takes about 35s. Currently I am running hugchat==0.3.1 with python 3.9.12

def chatbot_response(email, passwd, input_text):
    # Try to load cookies from the fixed directory
    try:
        sign = Login(email, None)
        cookies = sign.loadCookiesFromDir(COOKIE_PATH_DIR)
    except Exception as e:
        # If loading cookies fails, perform a new login
        sign = Login(email, passwd)
        cookies = sign.login()
        sign.saveCookiesToDir(COOKIE_PATH_DIR)

    # Create a ChatBot
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

    # Create a new conversation
    conversation_id = chatbot.new_conversation()

    # Set the current conversation context
    chatbot.change_conversation(conversation_id)

    # Send the predefined input text to the chatbot
    response_dict = chatbot.query(
        text=input_text,
        temperature=0.2,
        max_new_tokens=1024,  # Experiment with a lower value
        top_k=10,  # Experiment with lower values
        top_p=0.7,  # Experiment with lower values
        use_cache=True,  # Enable response caching
        repetition_penalty=1.0,
        retry_count=2,  # Set the retry_count to a lower value, e.g., 2
        stream=False  # Disable streaming to get the entire response at once
    )

    # End the conversation (optional)
    chatbot.new_conversation()

    # Extract 'text' from the response dictionary
    if 'text' in response_dict:
        response_text = response_dict['text']
    else:
        response_text = "No 'text' field found in the response dictionary."

    # Ensure response is 2 to 3 sentences
    sentences = response_text.split('.')
    response_text = '. '.join(sentences[:3])

    # Ensure response ends with a full stop
    if not response_text.endswith('.'):
            response_text += '.'

    return response_text
This is my codes it is taking 43.59 seconds to execute.  how to reduce this

**Comment by AravindRohit** [comment]
I am using latest version before previous version it was executing fast within 10 seconds

**Comment by RockChinQ** [comment]
#104

**Comment by RockChinQ** [comment]
> tell me a joke

For this case, I didn't meet such issue with latest version.

```python
# code
from hugchat import hugchat
from hugchat.login import Login

import time

print(time.time())

sign = Login("email", "pwd")
cookies = sign.login()

cookie_path_dir = "./cookies"
sign.saveCookiesToDir(cookie_path_dir)

print(time.time())

chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

query_result = chatbot.chat("tell me a joke")

print(query_result)

print(time.time())
```

And output here:

```

@RockChinQ ➜ /workspaces/hugging-chat-api/src (master) $ python test_noncli.py 
1696432249.6341772
1696432251.4375608
Sure, here's one for you:

Why don't scientists trust atoms?

Because they make up everything!

I hope that brought a smile to your face! Is there anything else I can assist you with?
1696432257.824509
@RockChinQ ➜ /workspaces/hugging-chat-api/src (master) $
```

I noticed that you've set a proxy, you can check if this is a proxy issue. Meanwhile, I'll check other cases for you now.
