### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'

### ISSUE THREAD

**Issue by IntelligenzaArtificiale** [Soulter/hugging-chat-api#87]
Hi guys,

i have this error with new version 

```
class ChatBot:

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 494, in ChatBot

    ) -> typing.Generator[dict, None, None] | dict:

TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'
```

**Comment by Soulter** [comment]
"|" is not available on python3.9. We'll fix it soon to adapt lower python interpreters

**Comment by IntelligenzaArtificiale** [comment]
thank you, you are the best 🤗

**Comment by IntelligenzaArtificiale** [comment]
I Love u guys 🚀

I have some app based on our api 😅

Could it help you if I develop a custom LLM connector for your API's langchain?

Some time ago with your bee I managed to run AUTOGPT without paying the API.

With this custom langchain LLM wrapper anyone can develop for free app like talk with pdf, python interpreter, etc...

Let me know if you're interested :)

**Comment by Soulter** [comment]
> I Love u guys 🚀
> 
> I have some app based on our api 😅
> 
> Could it help you if I develop a custom LLM connector for your API's langchain?
> 
> Some time ago with your bee I managed to run AUTOGPT without paying the API.
> 
> With this custom langchain LLM wrapper anyone can develop for free app like talk with pdf, python interpreter, etc...
> 
> Let me know if you're interested :)

wow that's cool, feel free to develop it!

**Comment by IntelligenzaArtificiale** [comment]
Hy guys 🚀,
I hope I don't disturb you.

I developed LLM langchain custom wrapper. Now you can use this api with langchain in a similar way to how OpenAI models are used.

Try this example:
This example demonstrates how to use HCA to interact with a language model to answer a question based on a context template. Users can modify the query in the prompt_template.format() call to ask different questions and get responses from the language model. This showcases the flexibility of HCA in handling various NLP tasks.

```python
from HCA import HCA
from langchain import PromptTemplate

# Initialize the HCA instance with your HuggingFace credentials
llm = HCA(email="YOUR_EMAIL", password="YOUR_PASSWORD", log=True, model=1)

# Define a template for your prompt
template = """Answer the question based on the context below. If the
question cannot be answered using the information provided, answer
with "I don't know".

Context: Large Language Models (LLMs) are the latest models used in NLP.
Their superior performance over smaller models has made them incredibly
useful for developers building NLP-enabled applications. These models
can be accessed via Hugging Face's `transformers` library, via OpenAI
using the `openai` library, and via Cohere using the `cohere` library.

Question: {query}

Answer: """

# Create a PromptTemplate for generating prompts
prompt_template = PromptTemplate(
    input_variables=["query"],
    template=template
)

# Generate a response to a specific question
response = llm(
    prompt_template.format(
        query="Which libraries and model providers offer LLMs?"
    )
)

print(response)
```

[LINK FOR CUSTOM LL WRAPPER🤗](https://github.com/IntelligenzaArtificiale/hugging-chat-api-LLM-custom-Wrapper/tree/main)

**Comment by IntelligenzaArtificiale** [comment]
Now evryone can create and develop custom langchain agent based on HuggingChat model :)

**Comment by IntelligenzaArtificiale** [comment]
This is another simple example that shows the potential of the custom langchain connector.


```python
from HCA import HCA

from langchain.agents import initialize_agent, AgentType
from langchain.tools.yahoo_finance_news import YahooFinanceNewsTool


llm = HCA(email="yourEmail", password="YourPSW" , model=0, temperature=0.1)

tools = [YahooFinanceNewsTool()]
agent_chain = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
)

agent_chain.run(
    "What happens today with Microsoft stocks?",
)
```
