### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by wambugu71** [Soulter/hugging-chat-api#89]
Error generated.
``` Python 
File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/login.py", line 126, in login

    location = self.getAuthURL()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/login.py", line 94, in getAuthURL

    raise Exception("Something went wrong!")

Exception: Something went wrong!
```

**Comment by ogios** [comment]
The server is down, don't know if they are updating or what else.

![Screenshot_2023-09-29-18-20-01-86_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Soulter/hugging-chat-api/assets/96933655/f04163a6-d512-4ac4-b7c1-593f743d2185)

**Comment by RockChinQ** [comment]
It works now.
