### ISSUE TITLE
How to use hugchat using token and avoiding adding username, password

### ISSUE THREAD

**Issue by andysingal** [Soulter/hugging-chat-api#95]
```
from hugchat.login import Login

# login
sign = Login("username", "password")
cookies = sign.login()
sign.saveCookiesToDir("/content")

# load cookies from usercookies
cookies = sign.loadCookiesFromDir("/content")
```

**Comment by Whitelisted1** [comment]
You are able to use a hugchat token instead of logging into your account by specifying a `cookie_path` when initializing the chatbot. See the code below:
```python
chatbot = hugchat.ChatBot(cookie_path=f"usercookies/{email}.json")
```

**Comment by andysingal** [comment]
> You are able to use a hugchat token instead of logging into your account by specifying a `cookie_path` when initializing the chatbot. See the code below:
> 
> ```python
> chatbot = hugchat.ChatBot(cookie_path=f"usercookies/{email}.json")
> ```

i was using huggingface username and password? . Can you please share the steps. Thanks

**Comment by Whitelisted1** [comment]
I'm unsure what you are asking. If you want to fetch a token for huggingchat using an email and password, you can refer to to the [example](https://github.com/Soulter/hugging-chat-api#api).

Here is a modified version:
```python
sign = Login(email, passwd)
cookies = sign.login()

# Save cookies to the local directory
cookie_path_dir = "./usercookies"
sign.saveCookiesToDir(cookie_path_dir)

# Load cookies when you restart your program:
# sign = login(email, None)
# cookies = sign.loadCookiesFromDir(cookie_path_dir) # This will detect if the JSON file exists, return cookies if it does and raise an Exception if it's not.

# Create a ChatBot
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())  # or cookie_path="usercookies/<email>.json"
```

**Comment by cydal** [comment]
I'm deploying an app in Spaces but as a final step, I wish to send a query to huggingchat. Is there a way to send in a query and get a response without adding my username/password or token?

**Comment by Whitelisted1** [comment]
> I'm deploying an app in Spaces but as a final step, I wish to send a query to huggingchat. Is there a way to send in a query and get a response without adding my username/password or token?

No, you can no longer get a response from HuggingChat without authorization

**Comment by ogios** [comment]
i dont know if the huggingface.co/chat gives access to guests
without the token then you will be recognized as a guest

**Comment by cydal** [comment]
Quick responses. Thanks guys! I think I'll create a dummy account and use it only to authorize the chat.

**Comment by afriaapi** [comment]
MissingSchema                             Traceback (most recent call last)
<ipython-input-6-ed4a037e298e> in <cell line: 23>()
     21 
     22 prompt = "What is Streamlit?"
---> 23 response = generate_response(prompt, hf_email, hf_pass)
     24 
     25 

9 frames
<ipython-input-6-ed4a037e298e> in generate_response(prompt_input, email, passwd)
     14     # Hugging Face Login
     15     sign = Login(email, passwd)
---> 16     cookies = sign.login()
     17     # Create ChatBot
     18     chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

/usr/local/lib/python3.10/dist-packages/hugchat/login.py in login(self)
    125         self.SigninWithEmail()
    126         location = self.getAuthURL()
--> 127         if self.grantAuth(location):
    128             return self.cookies
    129         else:

/usr/local/lib/python3.10/dist-packages/hugchat/login.py in grantAuth(self, url)
     98         if res.headers.__contains__("location"):
     99             location = res.headers["location"]
--> 100             res = self.requestsGet(location, allow_redirects=False)
    101             if res.cookies.__contains__("hf-chat"):
    102                 return 1

/usr/local/lib/python3.10/dist-packages/hugchat/login.py in requestsGet(self, url, params, allow_redirects)
     26 
     27     def requestsGet(self, url: str, params=None, allow_redirects=True) -> requests.Response:
---> 28         res = requests.get(
     29             url,
     30             params=params,

/usr/local/lib/python3.10/dist-packages/requests/api.py in get(url, params, **kwargs)
     71     """
     72 
---> 73     return request("get", url, params=params, **kwargs)
     74 
     75 

/usr/local/lib/python3.10/dist-packages/requests/api.py in request(method, url, **kwargs)
     57     # cases, and look like a memory leak in others.
     58     with sessions.Session() as session:
---> 59         return session.request(method=method, url=url, **kwargs)
     60 
     61 

/usr/local/lib/python3.10/dist-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    573             hooks=hooks,
    574         )
--> 575         prep = self.prepare_request(req)
    576 
    577         proxies = proxies or {}

/usr/local/lib/python3.10/dist-packages/requests/sessions.py in prepare_request(self, request)
    484 
    485         p = PreparedRequest()
--> 486         p.prepare(
    487             method=request.method.upper(),
    488             url=request.url,

/usr/local/lib/python3.10/dist-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    366 
    367         self.prepare_method(method)
--> 368         self.prepare_url(url, params)
    369         self.prepare_headers(headers)
    370         self.prepare_cookies(cookies)

/usr/local/lib/python3.10/dist-packages/requests/models.py in prepare_url(self, url, params)
    437 
    438         if not scheme:
--> 439             raise MissingSchema(
    440                 f"Invalid URL {url!r}: No scheme supplied. "
    441                 f"Perhaps you meant https://{url}?"

MissingSchema: Invalid URL '/login?next=%2Foauth%2Fauthorize%3Fclient_id%3D8f1a1d63-479b-46c8-84cb-521fe9f3222f%26scope%3Dopenid%2520profile%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fhuggingface.co%252Fchat%252Flogin%252Fcallback%26state%3DeyJkYXRhIjp7ImV4cGlyYXRpb24iOjE3MDA3Mzg1Njk4MjcsInJlZGlyZWN0VXJsIjoiaHR0cHM6Ly9odWdnaW5nZmFjZS5jby9jaGF0L2xvZ2luL2NhbGxiYWNrIn0sInNpZ25hdHVyZSI6IjdlNThmOGM5NzRjZmMyNmQ4OGVjMWY2YzNjM2ViYjU0ZTVhNWU2YmUyMWRlMjc0YmViNDU1NWMzNjI4NTlhZWQifQ%253D%253D': No scheme supplied. Perhaps you meant https:///login?next=%2Foauth%2Fauthorize%3Fclient_id%3D8f1a1d63-479b-46c8-84cb-521fe9f3222f%26scope%3Dopenid%2520profile%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fhuggingface.co%252Fchat%252Flogin%252Fcallback%26state%3DeyJkYXRhIjp7ImV4cGlyYXRpb24iOjE3MDA3Mzg1Njk4MjcsInJlZGlyZWN0VXJsIjoiaHR0cHM6Ly9odWdnaW5nZmFjZS5jby9jaGF0L2xvZ2luL2NhbGxiYWNrIn0sInNpZ25hdHVyZSI6IjdlNThmOGM5NzRjZmMyNmQ4OGVjMWY2YzNjM2ViYjU0ZTVhNWU2YmUyMWRlMjc0YmViNDU1NWMzNjI4NTlhZWQifQ%253D%253D?

**Comment by amandaoneallakeside** [comment]
Does anyone know what causes the MissingSchema error that afriaapi posted? I'm running into the same thing.

**Comment by Whitelisted1** [comment]
> Does anyone know what causes the MissingSchema error that afriaapi posted? I'm running into the same thing.

Please check out #138
