### ISSUE TITLE
Is OpenAssistant/oasst-sft-6-llama-30b-xor working? On HF interface, this model is removed from switch menu.

### ISSUE THREAD

**Issue by hansfzlorenzana** [Soulter/hugging-chat-api#98]
<img width="507" alt="image" src="https://github.com/Soulter/hugging-chat-api/assets/47592497/485a0e7e-67cc-412d-a977-566c18f2bfe0">

Please check https://huggingface.co/chat/ to confirm.

**Comment by Whitelisted1** [comment]
No, it is not, and when you try to switch to that model it raises an error
I created a poll request to remove it from the `llms` list
[Here's a link](https://github.com/Soulter/hugging-chat-api/pull/97#issuecomment-1742207412)
