### ISSUE TITLE
[Feature Request] Add language translation api

### ISSUE THREAD

**Issue by Soulter** [Soulter/hugging-chat-api#99]
The issue mainly explores the feasibility of adding translation api in the hugchat, such as Google translation, Bing translation and so on to solve the current problem that public LLMs on the hugchat only support English.

**Comment by ogios** [comment]
falcon (180b) supports well of other languages, but it's the only one

**Comment by Soulter** [comment]
> falcon (180b) supports well of other languages, but it's the only one

Ohh really? That's enough at all.

**Comment by RockChinQ** [comment]
Maybe a good idea to create a wrapper layer to implement such features, also decouple with protocol layer at the same time.

**Comment by IntelligenzaArtificiale** [comment]
I think I can easily integrate a "target_language" variable into this LLM wrapper and before returning the response it translates it into the desired language.  [LINK FOR CUSTOM LLM WRAPPER🤗](https://github.com/IntelligenzaArtificiale/hugging-chat-api-LLM-custom-Wrapper/tree/main)
